version: "3.9"
services:
  mothership:
    build: .
    container_name: mothership
    tty: true
    stdin_open: true
    env_file:
      - variables.env
    ports:
      - "8080:8080"
      - "443:443"
      - "22:22"
    volumes:
      - .:/mothership
